backend:
  name: github
  repo: "99bigdeal/chalisa-hugo"
  branch: "main"
  site_url: https://chalisa-hugo.pages.dev
  base_url: https://chalisa-hugo.pages.dev
  auth_endpoint: /auth
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "chalisa"
    label: "Chalisa"
    folder: "content/chalisa"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Chalisa Text", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }