backend:
  name: github
  repo: 99bigdeal/chalisa-hugo
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "chalisa"
    label: "Chalisa"
    folder: "content/chalisa"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}